# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='token',
            field=models.CharField(default='SATAN', max_length=200, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
